import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;

public class MaxProfits {

	/*

	 	BitCoin which is having below different prices

	 	Day1 21138
	 	Day2 21517
	 	Day3 21416
	 	Day4 21829
	 	Day5 21600
	 	Day6 21365
	 	Day7 21565

	 	Consider if we buy the Bitcoin on Day1 for => 21138
	 	And we Sell it on Day7 for 				   => 21565
	 	Profit =>								-  => 427		+ve => Profit

	 	Consider if we buy the Bitcoin on Day4 for => 21829
	 	And we Sell it on Day6 for 				   => 21365
	 	Profit =>								-  => -464		-ve => Loss

	 	Find the Maximum Profit which can be generated by purchasing the BitCoin on a day and selling it some other day
	 */

    static int getMaxProfit(Integer[] prices) {

        int maxProfit = 0;

/*        for(int i=0; i<prices.length; i++){
            for(int j=0; j<prices.length; j++){
                int profit = prices[i]-prices[j];
                if(profit>maxProfit) {
                    maxProfit = profit;
                }
            }
        }*/

        Arrays.sort(prices, Collections.reverseOrder());
        maxProfit = prices[0]-prices[prices.length-1];


        return maxProfit;

    }

    public static void main(String[] args) {

        Integer[] bitCoinPriceWeekly = {21138, 21517, 21416, 21829, 21600, 21365, 21565};
        int maxProfit = getMaxProfit(bitCoinPriceWeekly);
        System.out.println("Max Profit is: "+maxProfit);

    }

}